package com.xkh.dao.bean;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class UsersExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table users
     *
     * @mbggenerated Sun Jan 15 20:12:48 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table users
     *
     * @mbggenerated Sun Jan 15 20:12:48 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table users
     *
     * @mbggenerated Sun Jan 15 20:12:48 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbggenerated Sun Jan 15 20:12:48 CST 2017
     */
    public UsersExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbggenerated Sun Jan 15 20:12:48 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbggenerated Sun Jan 15 20:12:48 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbggenerated Sun Jan 15 20:12:48 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbggenerated Sun Jan 15 20:12:48 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbggenerated Sun Jan 15 20:12:48 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbggenerated Sun Jan 15 20:12:48 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbggenerated Sun Jan 15 20:12:48 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbggenerated Sun Jan 15 20:12:48 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbggenerated Sun Jan 15 20:12:48 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table users
     *
     * @mbggenerated Sun Jan 15 20:12:48 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table users
     *
     * @mbggenerated Sun Jan 15 20:12:48 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andEmailIsNull() {
            addCriterion("email is null");
            return (Criteria) this;
        }

        public Criteria andEmailIsNotNull() {
            addCriterion("email is not null");
            return (Criteria) this;
        }

        public Criteria andEmailEqualTo(String value) {
            addCriterion("email =", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotEqualTo(String value) {
            addCriterion("email <>", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThan(String value) {
            addCriterion("email >", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThanOrEqualTo(String value) {
            addCriterion("email >=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThan(String value) {
            addCriterion("email <", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThanOrEqualTo(String value) {
            addCriterion("email <=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLike(String value) {
            addCriterion("email like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotLike(String value) {
            addCriterion("email not like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailIn(List<String> values) {
            addCriterion("email in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotIn(List<String> values) {
            addCriterion("email not in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailBetween(String value1, String value2) {
            addCriterion("email between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotBetween(String value1, String value2) {
            addCriterion("email not between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andUsertelIsNull() {
            addCriterion("userTel is null");
            return (Criteria) this;
        }

        public Criteria andUsertelIsNotNull() {
            addCriterion("userTel is not null");
            return (Criteria) this;
        }

        public Criteria andUsertelEqualTo(String value) {
            addCriterion("userTel =", value, "usertel");
            return (Criteria) this;
        }

        public Criteria andUsertelNotEqualTo(String value) {
            addCriterion("userTel <>", value, "usertel");
            return (Criteria) this;
        }

        public Criteria andUsertelGreaterThan(String value) {
            addCriterion("userTel >", value, "usertel");
            return (Criteria) this;
        }

        public Criteria andUsertelGreaterThanOrEqualTo(String value) {
            addCriterion("userTel >=", value, "usertel");
            return (Criteria) this;
        }

        public Criteria andUsertelLessThan(String value) {
            addCriterion("userTel <", value, "usertel");
            return (Criteria) this;
        }

        public Criteria andUsertelLessThanOrEqualTo(String value) {
            addCriterion("userTel <=", value, "usertel");
            return (Criteria) this;
        }

        public Criteria andUsertelLike(String value) {
            addCriterion("userTel like", value, "usertel");
            return (Criteria) this;
        }

        public Criteria andUsertelNotLike(String value) {
            addCriterion("userTel not like", value, "usertel");
            return (Criteria) this;
        }

        public Criteria andUsertelIn(List<String> values) {
            addCriterion("userTel in", values, "usertel");
            return (Criteria) this;
        }

        public Criteria andUsertelNotIn(List<String> values) {
            addCriterion("userTel not in", values, "usertel");
            return (Criteria) this;
        }

        public Criteria andUsertelBetween(String value1, String value2) {
            addCriterion("userTel between", value1, value2, "usertel");
            return (Criteria) this;
        }

        public Criteria andUsertelNotBetween(String value1, String value2) {
            addCriterion("userTel not between", value1, value2, "usertel");
            return (Criteria) this;
        }

        public Criteria andSexIsNull() {
            addCriterion("sex is null");
            return (Criteria) this;
        }

        public Criteria andSexIsNotNull() {
            addCriterion("sex is not null");
            return (Criteria) this;
        }

        public Criteria andSexEqualTo(Byte value) {
            addCriterion("sex =", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotEqualTo(Byte value) {
            addCriterion("sex <>", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexGreaterThan(Byte value) {
            addCriterion("sex >", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexGreaterThanOrEqualTo(Byte value) {
            addCriterion("sex >=", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLessThan(Byte value) {
            addCriterion("sex <", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLessThanOrEqualTo(Byte value) {
            addCriterion("sex <=", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexIn(List<Byte> values) {
            addCriterion("sex in", values, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotIn(List<Byte> values) {
            addCriterion("sex not in", values, "sex");
            return (Criteria) this;
        }

        public Criteria andSexBetween(Byte value1, Byte value2) {
            addCriterion("sex between", value1, value2, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotBetween(Byte value1, Byte value2) {
            addCriterion("sex not between", value1, value2, "sex");
            return (Criteria) this;
        }

        public Criteria andUsernameIsNull() {
            addCriterion("userName is null");
            return (Criteria) this;
        }

        public Criteria andUsernameIsNotNull() {
            addCriterion("userName is not null");
            return (Criteria) this;
        }

        public Criteria andUsernameEqualTo(String value) {
            addCriterion("userName =", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotEqualTo(String value) {
            addCriterion("userName <>", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameGreaterThan(String value) {
            addCriterion("userName >", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameGreaterThanOrEqualTo(String value) {
            addCriterion("userName >=", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLessThan(String value) {
            addCriterion("userName <", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLessThanOrEqualTo(String value) {
            addCriterion("userName <=", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLike(String value) {
            addCriterion("userName like", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotLike(String value) {
            addCriterion("userName not like", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameIn(List<String> values) {
            addCriterion("userName in", values, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotIn(List<String> values) {
            addCriterion("userName not in", values, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameBetween(String value1, String value2) {
            addCriterion("userName between", value1, value2, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotBetween(String value1, String value2) {
            addCriterion("userName not between", value1, value2, "username");
            return (Criteria) this;
        }

        public Criteria andUserpwdIsNull() {
            addCriterion("userPwd is null");
            return (Criteria) this;
        }

        public Criteria andUserpwdIsNotNull() {
            addCriterion("userPwd is not null");
            return (Criteria) this;
        }

        public Criteria andUserpwdEqualTo(String value) {
            addCriterion("userPwd =", value, "userpwd");
            return (Criteria) this;
        }

        public Criteria andUserpwdNotEqualTo(String value) {
            addCriterion("userPwd <>", value, "userpwd");
            return (Criteria) this;
        }

        public Criteria andUserpwdGreaterThan(String value) {
            addCriterion("userPwd >", value, "userpwd");
            return (Criteria) this;
        }

        public Criteria andUserpwdGreaterThanOrEqualTo(String value) {
            addCriterion("userPwd >=", value, "userpwd");
            return (Criteria) this;
        }

        public Criteria andUserpwdLessThan(String value) {
            addCriterion("userPwd <", value, "userpwd");
            return (Criteria) this;
        }

        public Criteria andUserpwdLessThanOrEqualTo(String value) {
            addCriterion("userPwd <=", value, "userpwd");
            return (Criteria) this;
        }

        public Criteria andUserpwdLike(String value) {
            addCriterion("userPwd like", value, "userpwd");
            return (Criteria) this;
        }

        public Criteria andUserpwdNotLike(String value) {
            addCriterion("userPwd not like", value, "userpwd");
            return (Criteria) this;
        }

        public Criteria andUserpwdIn(List<String> values) {
            addCriterion("userPwd in", values, "userpwd");
            return (Criteria) this;
        }

        public Criteria andUserpwdNotIn(List<String> values) {
            addCriterion("userPwd not in", values, "userpwd");
            return (Criteria) this;
        }

        public Criteria andUserpwdBetween(String value1, String value2) {
            addCriterion("userPwd between", value1, value2, "userpwd");
            return (Criteria) this;
        }

        public Criteria andUserpwdNotBetween(String value1, String value2) {
            addCriterion("userPwd not between", value1, value2, "userpwd");
            return (Criteria) this;
        }

        public Criteria andUsersaltIsNull() {
            addCriterion("userSalt is null");
            return (Criteria) this;
        }

        public Criteria andUsersaltIsNotNull() {
            addCriterion("userSalt is not null");
            return (Criteria) this;
        }

        public Criteria andUsersaltEqualTo(String value) {
            addCriterion("userSalt =", value, "usersalt");
            return (Criteria) this;
        }

        public Criteria andUsersaltNotEqualTo(String value) {
            addCriterion("userSalt <>", value, "usersalt");
            return (Criteria) this;
        }

        public Criteria andUsersaltGreaterThan(String value) {
            addCriterion("userSalt >", value, "usersalt");
            return (Criteria) this;
        }

        public Criteria andUsersaltGreaterThanOrEqualTo(String value) {
            addCriterion("userSalt >=", value, "usersalt");
            return (Criteria) this;
        }

        public Criteria andUsersaltLessThan(String value) {
            addCriterion("userSalt <", value, "usersalt");
            return (Criteria) this;
        }

        public Criteria andUsersaltLessThanOrEqualTo(String value) {
            addCriterion("userSalt <=", value, "usersalt");
            return (Criteria) this;
        }

        public Criteria andUsersaltLike(String value) {
            addCriterion("userSalt like", value, "usersalt");
            return (Criteria) this;
        }

        public Criteria andUsersaltNotLike(String value) {
            addCriterion("userSalt not like", value, "usersalt");
            return (Criteria) this;
        }

        public Criteria andUsersaltIn(List<String> values) {
            addCriterion("userSalt in", values, "usersalt");
            return (Criteria) this;
        }

        public Criteria andUsersaltNotIn(List<String> values) {
            addCriterion("userSalt not in", values, "usersalt");
            return (Criteria) this;
        }

        public Criteria andUsersaltBetween(String value1, String value2) {
            addCriterion("userSalt between", value1, value2, "usersalt");
            return (Criteria) this;
        }

        public Criteria andUsersaltNotBetween(String value1, String value2) {
            addCriterion("userSalt not between", value1, value2, "usersalt");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNull() {
            addCriterion("createTime is null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNotNull() {
            addCriterion("createTime is not null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeEqualTo(Date value) {
            addCriterion("createTime =", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotEqualTo(Date value) {
            addCriterion("createTime <>", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThan(Date value) {
            addCriterion("createTime >", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("createTime >=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThan(Date value) {
            addCriterion("createTime <", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThanOrEqualTo(Date value) {
            addCriterion("createTime <=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIn(List<Date> values) {
            addCriterion("createTime in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotIn(List<Date> values) {
            addCriterion("createTime not in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeBetween(Date value1, Date value2) {
            addCriterion("createTime between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotBetween(Date value1, Date value2) {
            addCriterion("createTime not between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIsNull() {
            addCriterion("updateTime is null");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIsNotNull() {
            addCriterion("updateTime is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeEqualTo(Date value) {
            addCriterion("updateTime =", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotEqualTo(Date value) {
            addCriterion("updateTime <>", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeGreaterThan(Date value) {
            addCriterion("updateTime >", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("updateTime >=", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeLessThan(Date value) {
            addCriterion("updateTime <", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeLessThanOrEqualTo(Date value) {
            addCriterion("updateTime <=", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIn(List<Date> values) {
            addCriterion("updateTime in", values, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotIn(List<Date> values) {
            addCriterion("updateTime not in", values, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeBetween(Date value1, Date value2) {
            addCriterion("updateTime between", value1, value2, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotBetween(Date value1, Date value2) {
            addCriterion("updateTime not between", value1, value2, "updatetime");
            return (Criteria) this;
        }

        public Criteria andLastlogtimeIsNull() {
            addCriterion("lastLogTime is null");
            return (Criteria) this;
        }

        public Criteria andLastlogtimeIsNotNull() {
            addCriterion("lastLogTime is not null");
            return (Criteria) this;
        }

        public Criteria andLastlogtimeEqualTo(Date value) {
            addCriterion("lastLogTime =", value, "lastlogtime");
            return (Criteria) this;
        }

        public Criteria andLastlogtimeNotEqualTo(Date value) {
            addCriterion("lastLogTime <>", value, "lastlogtime");
            return (Criteria) this;
        }

        public Criteria andLastlogtimeGreaterThan(Date value) {
            addCriterion("lastLogTime >", value, "lastlogtime");
            return (Criteria) this;
        }

        public Criteria andLastlogtimeGreaterThanOrEqualTo(Date value) {
            addCriterion("lastLogTime >=", value, "lastlogtime");
            return (Criteria) this;
        }

        public Criteria andLastlogtimeLessThan(Date value) {
            addCriterion("lastLogTime <", value, "lastlogtime");
            return (Criteria) this;
        }

        public Criteria andLastlogtimeLessThanOrEqualTo(Date value) {
            addCriterion("lastLogTime <=", value, "lastlogtime");
            return (Criteria) this;
        }

        public Criteria andLastlogtimeIn(List<Date> values) {
            addCriterion("lastLogTime in", values, "lastlogtime");
            return (Criteria) this;
        }

        public Criteria andLastlogtimeNotIn(List<Date> values) {
            addCriterion("lastLogTime not in", values, "lastlogtime");
            return (Criteria) this;
        }

        public Criteria andLastlogtimeBetween(Date value1, Date value2) {
            addCriterion("lastLogTime between", value1, value2, "lastlogtime");
            return (Criteria) this;
        }

        public Criteria andLastlogtimeNotBetween(Date value1, Date value2) {
            addCriterion("lastLogTime not between", value1, value2, "lastlogtime");
            return (Criteria) this;
        }

        public Criteria andPorovinceIsNull() {
            addCriterion("porovince is null");
            return (Criteria) this;
        }

        public Criteria andPorovinceIsNotNull() {
            addCriterion("porovince is not null");
            return (Criteria) this;
        }

        public Criteria andPorovinceEqualTo(Integer value) {
            addCriterion("porovince =", value, "porovince");
            return (Criteria) this;
        }

        public Criteria andPorovinceNotEqualTo(Integer value) {
            addCriterion("porovince <>", value, "porovince");
            return (Criteria) this;
        }

        public Criteria andPorovinceGreaterThan(Integer value) {
            addCriterion("porovince >", value, "porovince");
            return (Criteria) this;
        }

        public Criteria andPorovinceGreaterThanOrEqualTo(Integer value) {
            addCriterion("porovince >=", value, "porovince");
            return (Criteria) this;
        }

        public Criteria andPorovinceLessThan(Integer value) {
            addCriterion("porovince <", value, "porovince");
            return (Criteria) this;
        }

        public Criteria andPorovinceLessThanOrEqualTo(Integer value) {
            addCriterion("porovince <=", value, "porovince");
            return (Criteria) this;
        }

        public Criteria andPorovinceIn(List<Integer> values) {
            addCriterion("porovince in", values, "porovince");
            return (Criteria) this;
        }

        public Criteria andPorovinceNotIn(List<Integer> values) {
            addCriterion("porovince not in", values, "porovince");
            return (Criteria) this;
        }

        public Criteria andPorovinceBetween(Integer value1, Integer value2) {
            addCriterion("porovince between", value1, value2, "porovince");
            return (Criteria) this;
        }

        public Criteria andPorovinceNotBetween(Integer value1, Integer value2) {
            addCriterion("porovince not between", value1, value2, "porovince");
            return (Criteria) this;
        }

        public Criteria andUsertypeIsNull() {
            addCriterion("userType is null");
            return (Criteria) this;
        }

        public Criteria andUsertypeIsNotNull() {
            addCriterion("userType is not null");
            return (Criteria) this;
        }

        public Criteria andUsertypeEqualTo(Byte value) {
            addCriterion("userType =", value, "usertype");
            return (Criteria) this;
        }

        public Criteria andUsertypeNotEqualTo(Byte value) {
            addCriterion("userType <>", value, "usertype");
            return (Criteria) this;
        }

        public Criteria andUsertypeGreaterThan(Byte value) {
            addCriterion("userType >", value, "usertype");
            return (Criteria) this;
        }

        public Criteria andUsertypeGreaterThanOrEqualTo(Byte value) {
            addCriterion("userType >=", value, "usertype");
            return (Criteria) this;
        }

        public Criteria andUsertypeLessThan(Byte value) {
            addCriterion("userType <", value, "usertype");
            return (Criteria) this;
        }

        public Criteria andUsertypeLessThanOrEqualTo(Byte value) {
            addCriterion("userType <=", value, "usertype");
            return (Criteria) this;
        }

        public Criteria andUsertypeIn(List<Byte> values) {
            addCriterion("userType in", values, "usertype");
            return (Criteria) this;
        }

        public Criteria andUsertypeNotIn(List<Byte> values) {
            addCriterion("userType not in", values, "usertype");
            return (Criteria) this;
        }

        public Criteria andUsertypeBetween(Byte value1, Byte value2) {
            addCriterion("userType between", value1, value2, "usertype");
            return (Criteria) this;
        }

        public Criteria andUsertypeNotBetween(Byte value1, Byte value2) {
            addCriterion("userType not between", value1, value2, "usertype");
            return (Criteria) this;
        }

        public Criteria andUsershopnumIsNull() {
            addCriterion("userShopNum is null");
            return (Criteria) this;
        }

        public Criteria andUsershopnumIsNotNull() {
            addCriterion("userShopNum is not null");
            return (Criteria) this;
        }

        public Criteria andUsershopnumEqualTo(Integer value) {
            addCriterion("userShopNum =", value, "usershopnum");
            return (Criteria) this;
        }

        public Criteria andUsershopnumNotEqualTo(Integer value) {
            addCriterion("userShopNum <>", value, "usershopnum");
            return (Criteria) this;
        }

        public Criteria andUsershopnumGreaterThan(Integer value) {
            addCriterion("userShopNum >", value, "usershopnum");
            return (Criteria) this;
        }

        public Criteria andUsershopnumGreaterThanOrEqualTo(Integer value) {
            addCriterion("userShopNum >=", value, "usershopnum");
            return (Criteria) this;
        }

        public Criteria andUsershopnumLessThan(Integer value) {
            addCriterion("userShopNum <", value, "usershopnum");
            return (Criteria) this;
        }

        public Criteria andUsershopnumLessThanOrEqualTo(Integer value) {
            addCriterion("userShopNum <=", value, "usershopnum");
            return (Criteria) this;
        }

        public Criteria andUsershopnumIn(List<Integer> values) {
            addCriterion("userShopNum in", values, "usershopnum");
            return (Criteria) this;
        }

        public Criteria andUsershopnumNotIn(List<Integer> values) {
            addCriterion("userShopNum not in", values, "usershopnum");
            return (Criteria) this;
        }

        public Criteria andUsershopnumBetween(Integer value1, Integer value2) {
            addCriterion("userShopNum between", value1, value2, "usershopnum");
            return (Criteria) this;
        }

        public Criteria andUsershopnumNotBetween(Integer value1, Integer value2) {
            addCriterion("userShopNum not between", value1, value2, "usershopnum");
            return (Criteria) this;
        }

        public Criteria andUserprodnumIsNull() {
            addCriterion("userProdNum is null");
            return (Criteria) this;
        }

        public Criteria andUserprodnumIsNotNull() {
            addCriterion("userProdNum is not null");
            return (Criteria) this;
        }

        public Criteria andUserprodnumEqualTo(Integer value) {
            addCriterion("userProdNum =", value, "userprodnum");
            return (Criteria) this;
        }

        public Criteria andUserprodnumNotEqualTo(Integer value) {
            addCriterion("userProdNum <>", value, "userprodnum");
            return (Criteria) this;
        }

        public Criteria andUserprodnumGreaterThan(Integer value) {
            addCriterion("userProdNum >", value, "userprodnum");
            return (Criteria) this;
        }

        public Criteria andUserprodnumGreaterThanOrEqualTo(Integer value) {
            addCriterion("userProdNum >=", value, "userprodnum");
            return (Criteria) this;
        }

        public Criteria andUserprodnumLessThan(Integer value) {
            addCriterion("userProdNum <", value, "userprodnum");
            return (Criteria) this;
        }

        public Criteria andUserprodnumLessThanOrEqualTo(Integer value) {
            addCriterion("userProdNum <=", value, "userprodnum");
            return (Criteria) this;
        }

        public Criteria andUserprodnumIn(List<Integer> values) {
            addCriterion("userProdNum in", values, "userprodnum");
            return (Criteria) this;
        }

        public Criteria andUserprodnumNotIn(List<Integer> values) {
            addCriterion("userProdNum not in", values, "userprodnum");
            return (Criteria) this;
        }

        public Criteria andUserprodnumBetween(Integer value1, Integer value2) {
            addCriterion("userProdNum between", value1, value2, "userprodnum");
            return (Criteria) this;
        }

        public Criteria andUserprodnumNotBetween(Integer value1, Integer value2) {
            addCriterion("userProdNum not between", value1, value2, "userprodnum");
            return (Criteria) this;
        }

        public Criteria andUsersourceIsNull() {
            addCriterion("userSource is null");
            return (Criteria) this;
        }

        public Criteria andUsersourceIsNotNull() {
            addCriterion("userSource is not null");
            return (Criteria) this;
        }

        public Criteria andUsersourceEqualTo(Byte value) {
            addCriterion("userSource =", value, "usersource");
            return (Criteria) this;
        }

        public Criteria andUsersourceNotEqualTo(Byte value) {
            addCriterion("userSource <>", value, "usersource");
            return (Criteria) this;
        }

        public Criteria andUsersourceGreaterThan(Byte value) {
            addCriterion("userSource >", value, "usersource");
            return (Criteria) this;
        }

        public Criteria andUsersourceGreaterThanOrEqualTo(Byte value) {
            addCriterion("userSource >=", value, "usersource");
            return (Criteria) this;
        }

        public Criteria andUsersourceLessThan(Byte value) {
            addCriterion("userSource <", value, "usersource");
            return (Criteria) this;
        }

        public Criteria andUsersourceLessThanOrEqualTo(Byte value) {
            addCriterion("userSource <=", value, "usersource");
            return (Criteria) this;
        }

        public Criteria andUsersourceIn(List<Byte> values) {
            addCriterion("userSource in", values, "usersource");
            return (Criteria) this;
        }

        public Criteria andUsersourceNotIn(List<Byte> values) {
            addCriterion("userSource not in", values, "usersource");
            return (Criteria) this;
        }

        public Criteria andUsersourceBetween(Byte value1, Byte value2) {
            addCriterion("userSource between", value1, value2, "usersource");
            return (Criteria) this;
        }

        public Criteria andUsersourceNotBetween(Byte value1, Byte value2) {
            addCriterion("userSource not between", value1, value2, "usersource");
            return (Criteria) this;
        }

        public Criteria andCityIsNull() {
            addCriterion("city is null");
            return (Criteria) this;
        }

        public Criteria andCityIsNotNull() {
            addCriterion("city is not null");
            return (Criteria) this;
        }

        public Criteria andCityEqualTo(Integer value) {
            addCriterion("city =", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotEqualTo(Integer value) {
            addCriterion("city <>", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityGreaterThan(Integer value) {
            addCriterion("city >", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityGreaterThanOrEqualTo(Integer value) {
            addCriterion("city >=", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLessThan(Integer value) {
            addCriterion("city <", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLessThanOrEqualTo(Integer value) {
            addCriterion("city <=", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityIn(List<Integer> values) {
            addCriterion("city in", values, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotIn(List<Integer> values) {
            addCriterion("city not in", values, "city");
            return (Criteria) this;
        }

        public Criteria andCityBetween(Integer value1, Integer value2) {
            addCriterion("city between", value1, value2, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotBetween(Integer value1, Integer value2) {
            addCriterion("city not between", value1, value2, "city");
            return (Criteria) this;
        }

        public Criteria andIsdelIsNull() {
            addCriterion("isDel is null");
            return (Criteria) this;
        }

        public Criteria andIsdelIsNotNull() {
            addCriterion("isDel is not null");
            return (Criteria) this;
        }

        public Criteria andIsdelEqualTo(Byte value) {
            addCriterion("isDel =", value, "isdel");
            return (Criteria) this;
        }

        public Criteria andIsdelNotEqualTo(Byte value) {
            addCriterion("isDel <>", value, "isdel");
            return (Criteria) this;
        }

        public Criteria andIsdelGreaterThan(Byte value) {
            addCriterion("isDel >", value, "isdel");
            return (Criteria) this;
        }

        public Criteria andIsdelGreaterThanOrEqualTo(Byte value) {
            addCriterion("isDel >=", value, "isdel");
            return (Criteria) this;
        }

        public Criteria andIsdelLessThan(Byte value) {
            addCriterion("isDel <", value, "isdel");
            return (Criteria) this;
        }

        public Criteria andIsdelLessThanOrEqualTo(Byte value) {
            addCriterion("isDel <=", value, "isdel");
            return (Criteria) this;
        }

        public Criteria andIsdelIn(List<Byte> values) {
            addCriterion("isDel in", values, "isdel");
            return (Criteria) this;
        }

        public Criteria andIsdelNotIn(List<Byte> values) {
            addCriterion("isDel not in", values, "isdel");
            return (Criteria) this;
        }

        public Criteria andIsdelBetween(Byte value1, Byte value2) {
            addCriterion("isDel between", value1, value2, "isdel");
            return (Criteria) this;
        }

        public Criteria andIsdelNotBetween(Byte value1, Byte value2) {
            addCriterion("isDel not between", value1, value2, "isdel");
            return (Criteria) this;
        }

        public Criteria andIschangenameIsNull() {
            addCriterion("isChangeName is null");
            return (Criteria) this;
        }

        public Criteria andIschangenameIsNotNull() {
            addCriterion("isChangeName is not null");
            return (Criteria) this;
        }

        public Criteria andIschangenameEqualTo(Byte value) {
            addCriterion("isChangeName =", value, "ischangename");
            return (Criteria) this;
        }

        public Criteria andIschangenameNotEqualTo(Byte value) {
            addCriterion("isChangeName <>", value, "ischangename");
            return (Criteria) this;
        }

        public Criteria andIschangenameGreaterThan(Byte value) {
            addCriterion("isChangeName >", value, "ischangename");
            return (Criteria) this;
        }

        public Criteria andIschangenameGreaterThanOrEqualTo(Byte value) {
            addCriterion("isChangeName >=", value, "ischangename");
            return (Criteria) this;
        }

        public Criteria andIschangenameLessThan(Byte value) {
            addCriterion("isChangeName <", value, "ischangename");
            return (Criteria) this;
        }

        public Criteria andIschangenameLessThanOrEqualTo(Byte value) {
            addCriterion("isChangeName <=", value, "ischangename");
            return (Criteria) this;
        }

        public Criteria andIschangenameIn(List<Byte> values) {
            addCriterion("isChangeName in", values, "ischangename");
            return (Criteria) this;
        }

        public Criteria andIschangenameNotIn(List<Byte> values) {
            addCriterion("isChangeName not in", values, "ischangename");
            return (Criteria) this;
        }

        public Criteria andIschangenameBetween(Byte value1, Byte value2) {
            addCriterion("isChangeName between", value1, value2, "ischangename");
            return (Criteria) this;
        }

        public Criteria andIschangenameNotBetween(Byte value1, Byte value2) {
            addCriterion("isChangeName not between", value1, value2, "ischangename");
            return (Criteria) this;
        }

        public Criteria andIsfirstloginIsNull() {
            addCriterion("isFirstLogin is null");
            return (Criteria) this;
        }

        public Criteria andIsfirstloginIsNotNull() {
            addCriterion("isFirstLogin is not null");
            return (Criteria) this;
        }

        public Criteria andIsfirstloginEqualTo(Byte value) {
            addCriterion("isFirstLogin =", value, "isfirstlogin");
            return (Criteria) this;
        }

        public Criteria andIsfirstloginNotEqualTo(Byte value) {
            addCriterion("isFirstLogin <>", value, "isfirstlogin");
            return (Criteria) this;
        }

        public Criteria andIsfirstloginGreaterThan(Byte value) {
            addCriterion("isFirstLogin >", value, "isfirstlogin");
            return (Criteria) this;
        }

        public Criteria andIsfirstloginGreaterThanOrEqualTo(Byte value) {
            addCriterion("isFirstLogin >=", value, "isfirstlogin");
            return (Criteria) this;
        }

        public Criteria andIsfirstloginLessThan(Byte value) {
            addCriterion("isFirstLogin <", value, "isfirstlogin");
            return (Criteria) this;
        }

        public Criteria andIsfirstloginLessThanOrEqualTo(Byte value) {
            addCriterion("isFirstLogin <=", value, "isfirstlogin");
            return (Criteria) this;
        }

        public Criteria andIsfirstloginIn(List<Byte> values) {
            addCriterion("isFirstLogin in", values, "isfirstlogin");
            return (Criteria) this;
        }

        public Criteria andIsfirstloginNotIn(List<Byte> values) {
            addCriterion("isFirstLogin not in", values, "isfirstlogin");
            return (Criteria) this;
        }

        public Criteria andIsfirstloginBetween(Byte value1, Byte value2) {
            addCriterion("isFirstLogin between", value1, value2, "isfirstlogin");
            return (Criteria) this;
        }

        public Criteria andIsfirstloginNotBetween(Byte value1, Byte value2) {
            addCriterion("isFirstLogin not between", value1, value2, "isfirstlogin");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table users
     *
     * @mbggenerated do_not_delete_during_merge Sun Jan 15 20:12:48 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table users
     *
     * @mbggenerated Sun Jan 15 20:12:48 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}